name: Releases
on: 
  push:
    tags:
    - '*'
jobs:    
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - uses: actions/checkout@v4
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "release.tar.gz,foo/*.txt,module.json,module.zip"
    vtt:
        runs-on: ubuntu-latest
        steps:
        - uses: djlechuck/foundryvtt-publish-package-action@v1
          with:
              token: ${{ secrets.FOUNDRYVTT_RELEASE_TOKEN }}
              manifest: 'https://github.com/${{ github.repository }}/releases/download/${{  github.ref_name }}/system.json'
