name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
    - uses: Varriount/fvtt-autopublish@latest
      with:
        artifacts: "release.tar.gz,foo/*.txt,module.json,ancestries-by-sirniloc-dc20.zip"
        username: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
        password: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
        module-id: ${{ secrets.FOUNDRY_ADMIN_MODULE_ID }}
        manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_NAME }}/module.json
        manifest-file: ${{ env.MANIFEST_FILE_PATH }}
